import uuid
from datetime import date, datetime, timezone

from sqlalchemy import Boolean, Date, DateTime, ForeignKey, String, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class FarmAlert(Base):
    """A detected anomaly in a farm's NDVI/NDWI timeseries -- generated by
    SatelliteService's alert rules (backend/app/services/satellite_service.py),
    typically by the nightly scheduler job (app/jobs/scheduler.py).
    """

    __tablename__ = "farm_alerts"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    farm_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("farms.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # "ndvi_drop" | "below_benchmark" | "water_stress"
    alert_type: Mapped[str] = mapped_column(String(30), nullable=False)
    # "info" | "warning" | "critical"
    severity: Mapped[str] = mapped_column(String(20), nullable=False)
    message: Mapped[str] = mapped_column(String(500), nullable=False)

    # The image_date of the satellite pass that triggered this alert --
    # used both for display and to de-duplicate (see
    # FarmAlertRepository.exists): the nightly job runs against the same
    # historical passes repeatedly and must not create the same alert twice.
    detected_at: Mapped[date] = mapped_column(Date, nullable=False)

    is_read: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )
