"use client";

import Link from "next/link";
import { AlertTriangle, BellRing, Check, CheckCircle2, ChevronRight, Loader2, RefreshCw } from "lucide-react";
import { formatPassDate } from "@/components/SourceBadge";
import { useFarmAlerts } from "@/lib/hooks/useFarmAlerts";

const ALERT_TITLES: Record<string, string> = {
  ndvi_drop: "NDVI drop",
  below_benchmark: "Below crop benchmark",
  water_stress: "Possible water stress",
};

/**
 * Unread satellite alerts for a real farm (generated by the backend's
 * nightly job), each with a mark-as-read button. Read alerts drop out of
 * the strip immediately (optimistic update).
 */
export default function AlertsStrip({ farmId }: { farmId: string }) {
  const { unread, isLoading, isError, retry, markRead, markReadError } = useFarmAlerts(farmId);

  if (isLoading) {
    return (
      <div className="rounded-2xl bg-white border border-farm-border-color p-4 flex items-center gap-2 text-xs text-farm-muted">
        <Loader2 className="w-4 h-4 animate-spin" /> Checking satellite alerts…
      </div>
    );
  }

  if (isError) {
    return (
      <div className="rounded-2xl bg-red-50 border border-red-200 p-4 flex items-center justify-between gap-3 text-xs text-red-900">
        <span className="flex items-center gap-2">
          <AlertTriangle className="w-4 h-4" /> Couldn&apos;t load satellite alerts.
        </span>
        <button
          onClick={() => retry()}
          className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg border border-red-300 bg-white font-semibold hover:bg-red-100"
        >
          <RefreshCw className="w-3.5 h-3.5" /> Retry
        </button>
      </div>
    );
  }

  if (unread.length === 0) {
    return (
      <div className="rounded-2xl bg-emerald-50 border border-emerald-200 p-4 flex items-center gap-3">
        <span className="w-9 h-9 rounded-xl bg-emerald-100 text-emerald-700 flex items-center justify-center flex-shrink-0">
          <CheckCircle2 className="w-4 h-4" />
        </span>
        <div>
          <h3 className="text-sm font-bold text-farm-dark">No new satellite alerts</h3>
          <p className="text-xs text-farm-muted mt-0.5">
            Every clear Sentinel-2 pass is checked nightly for NDVI drops and water stress.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="rounded-2xl bg-amber-50 border border-amber-200 p-4 space-y-3">
      <div className="flex items-center justify-between gap-3">
        <h3 className="text-sm font-bold text-amber-950 flex items-center gap-2">
          <BellRing className="w-4 h-4 text-amber-700" />
          {unread.length} new satellite {unread.length === 1 ? "alert" : "alerts"}
        </h3>
        <Link
          href={`/satellite?farm=${farmId}`}
          className="text-xs font-bold text-amber-900 hover:underline flex items-center gap-0.5 flex-shrink-0"
        >
          View on map <ChevronRight className="w-3.5 h-3.5" />
        </Link>
      </div>
      <ul className="space-y-2">
        {unread.map((alert) => (
          <li
            key={alert.id}
            className="bg-white/80 border border-amber-200 rounded-xl p-3 flex flex-col sm:flex-row sm:items-center justify-between gap-2"
          >
            <div className="min-w-0">
              <div className="flex flex-wrap items-center gap-2">
                <span className="text-xs font-bold text-farm-dark">
                  {ALERT_TITLES[alert.alert_type] ?? alert.alert_type}
                </span>
                <span
                  className={`text-[10px] uppercase font-bold px-1.5 py-0.5 rounded ${
                    alert.severity === "critical" ? "bg-red-100 text-red-800" : "bg-amber-200 text-amber-900"
                  }`}
                >
                  {alert.severity}
                </span>
                <span className="text-[11px] text-farm-muted">Sentinel-2 pass {formatPassDate(alert.detected_at)}</span>
              </div>
              <p className="text-xs text-amber-950 mt-1">{alert.message}</p>
            </div>
            <button
              onClick={() => markRead(alert.id)}
              className="self-start sm:self-auto inline-flex items-center gap-1 px-2.5 py-1 rounded-lg border border-amber-300 bg-white text-[11px] font-semibold text-amber-900 hover:bg-amber-100 flex-shrink-0"
            >
              <Check className="w-3.5 h-3.5" /> Mark as read
            </button>
          </li>
        ))}
      </ul>
      {markReadError && <p className="text-[11px] text-red-700">Couldn&apos;t mark that alert as read — please try again.</p>}
    </div>
  );
}
