import uuid

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.deps import get_current_user
from app.models.farm_alert import FarmAlert
from app.models.user import User
from app.repositories.farm_alert_repository import FarmAlertRepository
from app.repositories.farm_repository import FarmRepository
from app.schemas.timeseries import FarmAlertResponse
from app.services.farm_service import FarmNotFoundError, FarmService

router = APIRouter(tags=["alerts"])


def get_farm_service(session: AsyncSession = Depends(get_db)) -> FarmService:
    return FarmService(FarmRepository(session))


def get_farm_alert_repository(session: AsyncSession = Depends(get_db)) -> FarmAlertRepository:
    return FarmAlertRepository(session)


@router.get("/farms/{farm_id}/alerts", response_model=list[FarmAlertResponse])
async def list_farm_alerts(
    farm_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    farm_service: FarmService = Depends(get_farm_service),
    farm_alert_repository: FarmAlertRepository = Depends(get_farm_alert_repository),
) -> list[FarmAlert]:
    """Most recent first. Generated by the nightly scheduler job
    (app/jobs/scheduler.py) via SatelliteService's alert rules -- this
    endpoint only reads what's already been detected."""
    try:
        farm = await farm_service.get_farm(current_user, farm_id)
    except FarmNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Farm not found.") from exc

    return await farm_alert_repository.list_by_farm(farm.id)


@router.patch("/alerts/{alert_id}/read", response_model=FarmAlertResponse)
async def mark_alert_read(
    alert_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_db),
) -> FarmAlert:
    """Marks one alert as read. Ownership is checked via the alert's farm
    (an alert has no user_id of its own) -- 404, never 403, if it's not
    yours or doesn't exist, matching the anti-enumeration pattern used
    throughout /farms."""
    farm_alert_repository = FarmAlertRepository(session)
    alert = await farm_alert_repository.get_by_id(alert_id)
    if alert is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Alert not found.")

    farm = await FarmRepository(session).get_by_id(alert.farm_id)
    if farm is None or farm.user_id != current_user.id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Alert not found.")

    return await farm_alert_repository.mark_read(alert)
