"""add environment_snapshots

Revision ID: 49ad5203c0bf
Revises: f8b4e9bfb4a7
Create Date: 2026-09-27 04:37:32.507544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ad5203c0bf'
down_revision: Union[str, None] = 'f8b4e9bfb4a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('rainfall_7d_mm', sa.Float(), nullable=False),
    sa.Column('rainfall_30d_mm', sa.Float(), nullable=False),
    sa.Column('rainfall_90d_mm', sa.Float(), nullable=False),
    sa.Column('rainfall_since_sowing_mm', sa.Float(), nullable=True),
    sa.Column('rainfall_as_of', sa.Date(), nullable=False),
    sa.Column('mean_lst_c', sa.Float(), nullable=True),
    sa.Column('hot_periods_60d', sa.Integer(), nullable=False),
    sa.Column('temperature_as_of', sa.Date(), nullable=False),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.Column('soil_moisture_as_of', sa.Date(), nullable=True),
    sa.Column('soil_ph', sa.Float(), nullable=True),
    sa.Column('soil_organic_carbon_g_per_kg', sa.Float(), nullable=True),
    sa.Column('soil_texture_class', sa.String(length=30), nullable=True),
    sa.Column('soil_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_snapshots_farm_id'), 'environment_snapshots', ['farm_id'], unique=True)
    # NOTE: autogenerate also proposed dropping 'spatial_ref_sys' -- that's
    # a PostGIS system table this app doesn't own, not a real schema change
    # (same false positive filtered out of every prior migration in this
    # repo). Deliberately not included here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_environment_snapshots_farm_id'), table_name='environment_snapshots')
    op.drop_table('environment_snapshots')
    # ### end Alembic commands ###
