"""market price daily series and stats

Revision ID: 4ab7ce48a836
Revises: ea7bbc36dd76
Create Date: 2026-09-27 15:36:46.113583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab7ce48a836'
down_revision: Union[str, None] = 'ea7bbc36dd76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_price_daily',
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('modal_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('arrival_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('weighted', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('market_id', 'commodity_id', 'date')
    )
    op.create_index('ix_market_price_daily_commodity_date', 'market_price_daily', ['commodity_id', 'date'], unique=False)
    op.create_index('ix_market_price_daily_state_commodity_date', 'market_price_daily', ['state_id', 'commodity_id', 'date'], unique=False)
    op.create_table('market_price_stats',
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('current_modal_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_min_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_arrival_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('avg_7d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avg_14d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avg_30d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('change_7d_pct', sa.Float(), nullable=True),
    sa.Column('change_30d_pct', sa.Float(), nullable=True),
    sa.Column('min_7d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_7d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_30d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_30d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volatility_30d_pct', sa.Float(), nullable=True),
    sa.Column('trading_days_30d', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(length=20), nullable=False),
    sa.Column('trend_change_pct', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('market_id', 'commodity_id')
    )
    op.create_index('ix_market_price_stats_state_commodity', 'market_price_stats', ['state_id', 'commodity_id'], unique=False)
    # (autogenerate's spatial_ref_sys drop removed -- PostGIS owns that table)
    op.add_column('markets', sa.Column('coordinate_precision', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'coordinate_precision')
    op.drop_index('ix_market_price_stats_state_commodity', table_name='market_price_stats')
    op.drop_table('market_price_stats')
    op.drop_index('ix_market_price_daily_state_commodity_date', table_name='market_price_daily')
    op.drop_index('ix_market_price_daily_commodity_date', table_name='market_price_daily')
    op.drop_table('market_price_daily')
    # ### end Alembic commands ###
