"""normalised market price schema

Replaces the flat mandi_prices/mandi_price_syncs tables (data.gov.in only,
never released) with a normalised catalogue + market_prices + ingestion
run/quality-issue logs.

Revision ID: 503f1c5fb314
Revises: 955dfa24bfab
Create Date: 2026-09-27 15:22:33.753229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '503f1c5fb314'
down_revision: Union[str, None] = '955dfa24bfab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('name_key', sa.String(length=150), nullable=False),
    sa.Column('commodity_group', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_commodities_name_key'), 'commodities', ['name_key'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_key', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('name_key')
    )
    op.create_table('price_ingestion_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('requests_made', sa.Integer(), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('records_flagged', sa.Integer(), nullable=False),
    sa.Column('notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_ingestion_runs_started_at'), 'price_ingestion_runs', ['started_at'], unique=False)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_key', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('name_key')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_key', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('state_id', 'name_key', name='uq_districts_state_name')
    )
    op.create_index(op.f('ix_districts_state_id'), 'districts', ['state_id'], unique=False)
    op.create_table('price_quality_issues',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['price_ingestion_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_quality_issues_code', 'price_quality_issues', ['code'], unique=False)
    op.create_index(op.f('ix_price_quality_issues_run_id'), 'price_quality_issues', ['run_id'], unique=False)
    op.create_table('varieties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=True),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('name_key', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_id', 'name_key', name='uq_varieties_commodity_name')
    )
    op.create_index(op.f('ix_varieties_commodity_id'), 'varieties', ['commodity_id'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('coordinate_source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_markets_district_id'), 'markets', ['district_id'], unique=False)
    op.create_index(op.f('ix_markets_state_id'), 'markets', ['state_id'], unique=False)
    op.create_index('ix_markets_state_name_key', 'markets', ['state_id', 'name_key'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('variety_id', sa.Integer(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('modal_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('arrival_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('arrival_unit', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('quality_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_record_id', name='uq_market_prices_source_record')
    )
    op.create_index(op.f('ix_market_prices_arrival_date'), 'market_prices', ['arrival_date'], unique=False)
    op.create_index('ix_market_prices_commodity_date', 'market_prices', ['commodity_id', 'arrival_date'], unique=False)
    op.create_index(op.f('ix_market_prices_commodity_id'), 'market_prices', ['commodity_id'], unique=False)
    op.create_index('ix_market_prices_market_commodity_date', 'market_prices', ['market_id', 'commodity_id', 'arrival_date'], unique=False)
    op.create_index(op.f('ix_market_prices_market_id'), 'market_prices', ['market_id'], unique=False)
    op.create_index('ix_market_prices_state_commodity_date', 'market_prices', ['state_id', 'commodity_id', 'arrival_date'], unique=False)
    op.drop_index(op.f('ix_mandi_prices_commodity_state_date'), table_name='mandi_prices')
    op.drop_table('mandi_prices')
    # (autogenerate's spatial_ref_sys drop removed -- PostGIS owns that table)
    op.drop_index(op.f('ix_mandi_price_syncs_started_at'), table_name='mandi_price_syncs')
    op.drop_table('mandi_price_syncs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandi_price_syncs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('succeeded', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('records_upserted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mandi_price_syncs_pkey'))
    )
    op.create_index(op.f('ix_mandi_price_syncs_started_at'), 'mandi_price_syncs', ['started_at'], unique=False)
    op.create_table('mandi_prices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('market', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('commodity', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('variety', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('grade', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('arrival_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('min_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('modal_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('mandi_prices_pkey')),
    sa.UniqueConstraint('market', 'commodity', 'variety', 'arrival_date', name=op.f('uq_mandi_prices_market_cmdt_var_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mandi_prices_commodity_state_date'), 'mandi_prices', ['commodity', 'state', 'arrival_date'], unique=False)
    op.drop_index('ix_market_prices_state_commodity_date', table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_market_id'), table_name='market_prices')
    op.drop_index('ix_market_prices_market_commodity_date', table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_commodity_id'), table_name='market_prices')
    op.drop_index('ix_market_prices_commodity_date', table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_arrival_date'), table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index('ix_markets_state_name_key', table_name='markets')
    op.drop_index(op.f('ix_markets_state_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_district_id'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_varieties_commodity_id'), table_name='varieties')
    op.drop_table('varieties')
    op.drop_index(op.f('ix_price_quality_issues_run_id'), table_name='price_quality_issues')
    op.drop_index('ix_price_quality_issues_code', table_name='price_quality_issues')
    op.drop_table('price_quality_issues')
    op.drop_index(op.f('ix_districts_state_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_table('states')
    op.drop_index(op.f('ix_price_ingestion_runs_started_at'), table_name='price_ingestion_runs')
    op.drop_table('price_ingestion_runs')
    op.drop_table('grades')
    op.drop_index(op.f('ix_commodities_name_key'), table_name='commodities')
    op.drop_table('commodities')
    # ### end Alembic commands ###
