"""add mandi prices and syncs

Revision ID: 955dfa24bfab
Revises: 49ad5203c0bf
Create Date: 2026-09-27 14:42:40.423520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955dfa24bfab'
down_revision: Union[str, None] = '49ad5203c0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerated; a false-positive drop of PostGIS's own spatial_ref_sys
    # table was removed by hand (as in every earlier migration).
    op.create_table('mandi_price_syncs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('records_upserted', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandi_price_syncs_started_at'), 'mandi_price_syncs', ['started_at'], unique=False)
    op.create_table('mandi_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=150), nullable=False),
    sa.Column('commodity', sa.String(length=150), nullable=False),
    sa.Column('variety', sa.String(length=150), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=False),
    sa.Column('modal_price', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'commodity', 'variety', 'arrival_date', name='uq_mandi_prices_market_cmdt_var_date')
    )
    op.create_index('ix_mandi_prices_commodity_state_date', 'mandi_prices', ['commodity', 'state', 'arrival_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mandi_prices_commodity_state_date', table_name='mandi_prices')
    op.drop_table('mandi_prices')
    op.drop_index(op.f('ix_mandi_price_syncs_started_at'), table_name='mandi_price_syncs')
    op.drop_table('mandi_price_syncs')
    # ### end Alembic commands ###
