"""price forecast models and forecasts

Revision ID: 9831a24d76b5
Revises: 4ab7ce48a836
Create Date: 2026-09-27 15:44:57.823023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9831a24d76b5'
down_revision: Union[str, None] = '4ab7ce48a836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_forecast_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('train_start', sa.Date(), nullable=False),
    sa.Column('train_end', sa.Date(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('n_markets', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('evaluation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('interval_low_log', sa.Float(), nullable=True),
    sa.Column('interval_high_log', sa.Float(), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_forecast_models_slot', 'price_forecast_models', ['commodity_id', 'state_id', 'horizon_days', 'is_active'], unique=False)
    op.create_table('price_forecasts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('base_date', sa.Date(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('predicted_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lower_bound', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('upper_bound', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['price_forecast_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'commodity_id', 'base_date', 'horizon_days', 'model_id', name='uq_price_forecast')
    )
    op.create_index('ix_price_forecasts_lookup', 'price_forecasts', ['market_id', 'commodity_id', 'generated_at'], unique=False)
    # (autogenerate's spatial_ref_sys drop removed -- PostGIS owns that table)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_forecasts_lookup', table_name='price_forecasts')
    op.drop_table('price_forecasts')
    op.drop_index('ix_price_forecast_models_slot', table_name='price_forecast_models')
    op.drop_table('price_forecast_models')
    # ### end Alembic commands ###
